version: '2'
services:
  nginx:
    image: guitcastro/nginx-w3c-trace-context
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./jaeger-config.json:/etc/jaeger-config.json
    expose:
      - "8080"
    ports:
      - "8080:8080"
  otel:
    image: otel/opentelemetry-collector-dev:latest
    volumes:
      - ./otel.yml:/conf/otel-collector-config.yml
    command: /otel --config=/conf/otel-collector-config.yml
    expose:
      - "6831/udp" # Default endpoint for Jaeger thrift_compact receiver
      - "55680"    # Default endpoint for OpenTelemetry receiver
      - "8888"     # Metrics
    ports:
      - "55680:55680"
      - "6831:6831/udp"
      - "8888:8888"      
  app-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "9001"
    ports:
      - "9001:9001"
    command: 
      - /app/server
      - -collector_host
      - jaeger

